name: smo_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  mobile_scanner: ^7.0.1
  syncfusion_flutter_charts: ^30.2.7
  file_picker: ^8.1.7
  excel: ^4.0.6
  spreadsheet_decoder: ^2.1.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  get: ^4.6.6
  multicast_dns: ^0.3.2+7
  path_provider: ^2.1.0
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true